import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Providers } from "./(redux)/provider";

const Mont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Renderr",
  description: "Generated by Renderr team",
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${Mont.className} bg-[#FCFCFC]`}>
          <div className="h-screen p-3">
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
